### ISSUE TITLE
The stylesheet for QDateTimeEdit

### ISSUE THREAD

**Issue by WhiteDew100** [UN-GCPDS/qt-material#11]
I found there are  no style for QDateTimeEdit,but there are styles for spinbox and doublebox . I had tried to write it ,but it didn't work when I run the application.
Can you add the style of  QDateTimeEdit  into the qt-material, thanks a lot .

`QDateTimeEdit::up-button{
  subcontrol-origin: border;
  subcontrol-position: top right;
  width: 20px; /* 16 + 2*1px border-width = 15px padding + 3px parent border */
  image: url(:/icon/primary/uparrow.svg);
  border-width: 0px;
  margin-right: 5px;
}
QDateTimeEdit::up-button:disabled{
  image: url(:/icon/disabled/uparrow.svg);
}
QDateTimeEdit::down-button {
  subcontrol-origin: border;
  subcontrol-position: bottom right;
  width: 20px;
  image: url(:/icon/primary/downarrow.svg);
  border-width: 0px;
  border-top-width: 0;
  margin-right: 5px;
}
QDateTimeEdit::down-button:disabled {
  image: url(:/icon/disabled/downarrow.svg);
}`

**Comment by YeisonCardona** [comment]
Hi @WhiteDew100, thanks for your contribution, now `QDateTimeEdit` share the same theme, and others that were missing too(`QLCDNumber` and `QCalendarWidget`) 
![Peek 2020-12-23 12-53](https://user-images.githubusercontent.com/4206584/103024797-88b79480-451e-11eb-9299-b2119053fb9e.gif)
