### ISSUE TITLE
QPushButton non-clickable areas

### ISSUE THREAD

**Issue by kohyuk91** [UN-GCPDS/qt-material#14]
![qpushbutton_issue](https://user-images.githubusercontent.com/20366898/105182654-a3f2df80-5b70-11eb-979e-7f406c5b1b04.png)

First of all, qt-material is awsome! Thank you for sharing this beautiful project with the community.

It seems like there are some non-clickable areas in the QPushButton. I've mark the non-clickable areas in red.
It's not much of an issue for big buttons(left), but for small buttons(right)  it's a bit of a challenge to click the 'clickable' area.

Using Windows10 by the way..

Hope this can be fixed!

**Comment by YeisonCardona** [comment]
Hi @kohyuk91, thanks for your support.

This is a [known bug](https://bugreports.qt.io/browse/QTBUG-86587) on Qt5, try to update to 5.15.2, this ffects both PyQt5 and PySide2.

``` shell
pip install -U pyqt5
pip install -U pyside2
```
or 
``` shell
pip install pyqt5==5.15.2
pip install pyside2==5.15.2
```

**Comment by kohyuk91** [comment]
> Hi @kohyuk91, thanks for your support.
> 
> This is a [known bug](https://bugreports.qt.io/browse/QTBUG-86587) on Qt5, try to update to 5.15.2, this ffects both PyQt5 and PySide2.
> 
> ``` shell
> pip install -U pyqt5
> pip install -U pyside2
> ```
> or 
> ``` shell
> pip install pyqt5==5.15.2
> pip install pyside2==5.15.2
> ```

Thank you for the quick response.
Upgrading to 5.15.2  did the trick!
