### ISSUE TITLE
Style 'Fusion' does not exist

### ISSUE THREAD

**Issue by Helios504** [UN-GCPDS/qt-material#15]
Apologies if this is user error.

I am able to successfully set a style with "apply_stylesheet"

`apply_stylesheet(self.window,theme='light_blue.xml')`

However whenever a button is pressed the following message is printed to the console:

> ERROR:root:The style 'Fusion' does not exist.

I get the same error message when i run the "runtime.py" file that is located in the examples folder from qt-material.

I'm running a basic QtWidget app with Python 3.9 and Pyside6.

Thanks

**Comment by YeisonCardona** [comment]
Hi @Helios504, `Fusion` was a default style for homogeneous looking under GNU/Linux and Windows, is not necessary now, I will remove the default style. Thanks.
