### ISSUE TITLE
QListView selection hard to read/different than QTableView/QTreeView

### ISSUE THREAD

**Issue by nicoddemus** [UN-GCPDS/qt-material#24]
Hi!

First of all thanks a lot for this package!

I noticed that the foreground and background color of the current selection for `QListView` controls is different than the colors used in `QTableView`/`QTreeView` (for the `dark_teal` theme):

**QListView**:

![image](https://user-images.githubusercontent.com/1085180/115119853-e023b980-9f80-11eb-89c3-dd0043fd0836.png)

**QTableView**/**QTreeView**:

![image](https://user-images.githubusercontent.com/1085180/115120184-70163300-9f82-11eb-8ac7-6fc5eecbbcab.png)

A simple workaround is to use a table with a single column and hide vertical and horizontal headers (as is the case with the screenshot above, that's a `QTableView`).

Thanks!

**Comment by YeisonCardona** [comment]
Hi @nicoddemus  
My `QListView` seems to look fine, can you share an example code?
Which is your operating system?, Are you using `PySide2`, `PySide6`, or `PyQt5`?

**Comment by nicoddemus** [comment]
Hi @YeisonCardona,

Thanks for the quick answer and sorry for the delay!

I'm using Windows, PyQt5. I will come up with an example which reproduces the issue later. 

Thanks!

**Comment by nicoddemus** [comment]
Hi @YeisonCardona,

Here's the example code:

```python
from PyQt5.QtWidgets import QListWidget, QApplication, QTreeWidget, QWidget, QHBoxLayout, \
    QTreeWidgetItem
from qt_material import apply_stylesheet

app = QApplication([])
apply_stylesheet(app, theme="dark_teal.xml")

list_widget = QListWidget()
list_widget.addItem("Item 1")
list_widget.addItem("Item 2")
list_widget.show()

tree_widget = QTreeWidget()
tree_widget.addTopLevelItem(QTreeWidgetItem(["Item 1"]))
tree_widget.addTopLevelItem(QTreeWidgetItem(["Item 2"]))
tree_widget.header().hide()

container = QWidget()
layout = QHBoxLayout(container)
layout.addWidget(list_widget)
layout.addWidget(tree_widget)
container.show()

app.exec()
``` 

Here are some screenshots:

![image](https://user-images.githubusercontent.com/1085180/115958522-1e1f6100-a4de-11eb-8b4e-bae21466f5de.png)

![image](https://user-images.githubusercontent.com/1085180/115958526-22e41500-a4de-11eb-9011-7816858dd43a.png)

![image](https://user-images.githubusercontent.com/1085180/115958530-26779c00-a4de-11eb-9df7-e44961a81aa4.png)

![image](https://user-images.githubusercontent.com/1085180/115958532-2b3c5000-a4de-11eb-8b78-e9a3fae004dc.png)

As you can see, the `QListWidget` (left) uses a black font for the text when selected, and there's a red outline indicating selection which is out of place with the rest of the theme.

Perhaps this is due to that I'm actually using a `QListWidget` instead of a `QListView`? Just now realized that's probably important information.

**Comment by YeisonCardona** [comment]
Hi @nicoddemus 

The focus outlines were totally unnoticed by me on my OS, I will add styles for them.

Since I have not a Windows machine near, can yo please help me to debug the following code, and tell me if the colors works with this changes.

``` python
from PyQt5.QtWidgets import QListWidget, QApplication, QTreeWidget, QWidget, QHBoxLayout, \
    QTreeWidgetItem
from qt_material import apply_stylesheet

app = QApplication([])
apply_stylesheet(app, theme="dark_teal.xml")

extra_css = """
QTreeView::item,
QListView::item {
  selection-color: red;
  selection-background-color: orange;
}
"""
app.setStyleSheet(app.styleSheet() + extra_css)

list_widget = QListWidget()
list_widget.addItem("Item 1")
list_widget.addItem("Item 2")
list_widget.show()

tree_widget = QTreeWidget()
tree_widget.addTopLevelItem(QTreeWidgetItem(["Item 1"]))
tree_widget.addTopLevelItem(QTreeWidgetItem(["Item 2"]))
tree_widget.header().hide()

container = QWidget()
layout = QHBoxLayout(container)
layout.addWidget(list_widget)
layout.addWidget(tree_widget)
container.show()

app.exec()

```

**Comment by nicoddemus** [comment]
Thanks for the quick answer!

Trying your code I get:

![image](https://user-images.githubusercontent.com/1085180/115971807-00272000-a521-11eb-9738-575f82635984.png)

![image](https://user-images.githubusercontent.com/1085180/115971811-0a491e80-a521-11eb-80cc-d0c018e5d6c9.png)

**Comment by YeisonCardona** [comment]
Do you think that black background on the non-focus item is the desired behavior?

I get
![Peek 2021-04-24 15-27](https://user-images.githubusercontent.com/4206584/115972036-b84ccc80-a511-11eb-8bde-8ef2c140215b.gif)

**Comment by nicoddemus** [comment]
That looks good, but I can't tell which one of them has keyboard focus... I believe widgets in general should have a focus indicator, as item selection and focus are separate properties. 

IOW, when you have a selection in both panels, the user can't tell which one has the focus, which is something important because events are sent to the item with focus: or up/down to navigate on the list, or depending on the selection mode press space to change the item selection.

Using the standard Windows theme:

No focus or selection in both panels:

![image](https://user-images.githubusercontent.com/1085180/115972295-dd4a3b00-a523-11eb-8188-8a5456ecc7ac.png)

Left: "Item 1" selected and with focus.
Right: No focus or selection.

![image](https://user-images.githubusercontent.com/1085180/115972302-ea672a00-a523-11eb-8c00-3564875683fe.png)

Left: "Item 1" selected.
Right: "Item 1" selected and with focus.
 
![image](https://user-images.githubusercontent.com/1085180/115972313-fbb03680-a523-11eb-9a6e-b4166e88e091.png)

Left: "Item 2" selected and with focus.
Right: "Item 1" selected.

![image](https://user-images.githubusercontent.com/1085180/115972363-3fa33b80-a524-11eb-8846-de9faab7d4c5.png)

**Comment by YeisonCardona** [comment]
In my OS the differences are practically imperceptive, this is the reason that this theme does not handle the focus (I'm not used to seeing them).

![Peek 2021-04-24 15-48](https://user-images.githubusercontent.com/4206584/115972567-ca7c3a00-a514-11eb-9d60-6834f5fe008b.gif)

I like the Windows behavior, could be something like:
![Peek 2021-04-24 19-48](https://user-images.githubusercontent.com/4206584/115976699-36bb6580-a536-11eb-8084-5fb189e6c198.gif)

**Comment by nicoddemus** [comment]
> In my OS the differences are practically imperceptive, this is the reason that this theme does not handle the focus (I'm not used to seeing them).

Ahh I see, thanks.

> I like the Windows behavior, could be something like:

IMHO that one looks great! 👍

**Comment by nicoddemus** [comment]
Seems like this has been released already? 😁 

If so we can close this (I would myself but would like for this to be confirmed first).

**Comment by YeisonCardona** [comment]
Hi @nicoddemus 
Seems like I forgot to write my response, sorry.
Yes, this is the new behavior.

**Comment by nicoddemus** [comment]
Cool, no worries!

Thanks again for the fix and release. 👍
