### ISSUE TITLE
Background color broken in linux

### ISSUE THREAD

**Issue by airabinovich** [UN-GCPDS/qt-material#26]
Hello,
I'm developing an application with PyQt5 and qt-material.
When I try the application in macOS it looked good but in ubuntu linux the background looks odd.
I'm using a dark theme and the background looks almost white so the text (labels, buttons, etc) is almost impossible to read
Versions that I'm using
```
qt-material==2.8.7
PyQt5==5.15.4
```

This is the way in what I'm using the library
```python3
class MainWindow(QWidget, QtStyleTools):

    def __init__(self):
        super().__init__()
        self.main = PyQt5.uic.loadUi('gui/screens/main_window.ui', self)
        self.apply_stylesheet(self.main, theme='dark_blue.xml')
```
I tried setting env var `QTMATERIAL_SECONDARYDARKCOLOR=#000000` and using `extra` attribute and nothing changed

Could you help me? Thanks

**Comment by YeisonCardona** [comment]
Hi @airabinovich 

The environment variables are not supposed to use for configuring the theme.
Even if is possible to change the theme variables with the `extra` argument and with the correct key (for example `secondaryDarkColor`) this is no the recommend way to do it.

Please refer to [custom colors](https://github.com/UN-GCPDS/qt-material#custom-colors) instructions.
