### ISSUE TITLE
Can't change to default themes

### ISSUE THREAD

**Issue by maicol07** [UN-GCPDS/qt-material#3]
After changing (in runtime) to a material theme, it's impossible to revert to a Qt default one (e.g. `windowsvista`)

**Comment by YeisonCardona** [comment]
On `GNU/Linux` the default theme is set just by applying an empty style with `QMainWindow.setStyleSheet('')`, which method are you using?, also, I add the `default` theme to the themes switcher menu.

**Comment by maicol07** [comment]
> On `GNU/Linux` the default theme is set just by applying an empty style with `QMainWindow.setStyleSheet('')`, which method are you using?, also, I add the `default` theme to the themes switcher menu.

No, on Windows we have 3 different standard themes: `windowsvista` (default), `windows` (xp like) and `Fusion`. To apply one of these themes, if that is not in `pyside_material.list_themes()` I use `QApplication.setStyle()`

**Comment by YeisonCardona** [comment]
Hi @maicol07, `windowsvista`, `windows` and `Fusion` are **Styles**, are different from the themes and works independently, you can change it with `apply_stylesheet` along with the theme.
```
apply_stylesheet(app, style='Fusion', theme='light_blue.xml')
```
