### ISSUE TITLE
Running examples no longer working

### ISSUE THREAD

**Issue by AdrianButnar** [UN-GCPDS/qt-material#30]
There is currently no `test` directory, let alone one containing any `main.py`.
A running example that works is in `/examples/full_features` and also the flag is changed from `--PySide6` to `pyside6`.
Updating the README.md would help others as well.

**Comment by YeisonCardona** [comment]
This is not an executable application, there is not need of a `main.py`.
_Examples_ is more clear that _test_ since this contains functional scripts and there is no way to perform _testing_ that debug visual styles and widgets issues.
Fixed the flag reference thanks.

**Comment by AdrianButnar** [comment]
The `main.py` was in your README in the wrong path, I did not say there was a need for one. 
What I was pointing out is that there was in no `test` directory in the repository as that directory does not exist, as your README erroneously pointed towards (see `cd test` in the Running examples section)
