### ISSUE TITLE
PySimpleGUIQT Support?

### ISSUE THREAD

**Issue by Bounty780** [UN-GCPDS/qt-material#31]
Working on a project that utilizes PySimpleGuiQT. The in-built styles don't seem to be any particularly better than recolored Windows 2000 buttons, so having an easy to use framework together with beautiful styles, it would be amazing.

**Comment by YeisonCardona** [comment]
Hi @Bounty780, I never hear about PySimpleGUI QT or even PySimpleGUI, I tried that modules and is awful to use, I don't see any advantages over PySide. But if you have access to the `QApplication` instance is possible to apply stylesheets.

**Comment by Bounty780** [comment]
Doesn't it use PySide as a base though? :/
