### ISSUE TITLE
RCC export file format incorrect

### ISSUE THREAD

**Issue by pstavirs** [UN-GCPDS/qt-material#44]
The rcc export is missing a closing `>` - `</qresource` instead of `</qresource>`

https://github.com/UN-GCPDS/qt-material/blob/master/qt_material/__init__.py#L72

**Comment by YeisonCardona** [comment]
Fixed https://github.com/UN-GCPDS/qt-material/commit/21fda8a692cc674a02ce3207dd971336250ab9c5
