### ISSUE TITLE
Input controls inside groupbox

### ISSUE THREAD

**Issue by pstavirs** [UN-GCPDS/qt-material#45]
The background color of input controls and groupbox is same, so they merge together. The bottom border helps to identify the input controls though. Here's an example -
![Capture](https://user-images.githubusercontent.com/8395079/146969254-4117291a-e241-47ba-89b8-31df5ef818ca.PNG)

I'm wondering if a groupbox should just be rendered with a border and not change the background color? I think material uses divider lines rather than boxes to group/separate content. Although that could be an option, it will likely not work in all cases - e.g. how to distinguish whether to use a vertical or horizontal divider? Top/Bottom? Left/Right?

Would it be better to render QGroupBox as a material card?

This is not really a bug, but a question of aesthetics, so I thought I'd open an issue to know your views

**Comment by YeisonCardona** [comment]
Hi @pstavirs 

I really like how looks without a different background color and just a border:

![Peek 2021-12-21 19-27](https://user-images.githubusercontent.com/4206584/147014979-5504c390-2921-4d15-a0c8-b053f3e59f6a.gif)

I will keep this look by default and the alternate background color with:
 ```my_qgroupbox.setProperty('class', 'fill_background')```
