### ISSUE TITLE
qt.svg Cannot open file ':/icon/primary ...', because: No such file or directory

### ISSUE THREAD

**Issue by lukasloetkolben** [UN-GCPDS/qt-material#6]
I get this error: qt.svg Cannot open file ':/icon/primary ...', because: No such file or directory
any solutions for that?

**Comment by YeisonCardona** [comment]
Hi, can you tell me about the operative system, the script that are you executing, are you working with the repository or with the pip installation?

**Comment by lukasloetkolben** [comment]
I am using Ubuntu. I installed it over pip.

**Comment by YeisonCardona** [comment]
This must be solved after edit the  [MANIFEST.in](https://github.com/UN-GCPDS/qt-material/commit/88995c4bff91f77fa0f821661a024486134e87d1#diff-41d5a52589e0480be9c099d2bba7a8135b8b0d71bcbb8df3582a8df1c2295003) to include all SVG files.
