### ISSUE TITLE
Text is being cut-off when using qt-designer to make the UI

### ISSUE THREAD

**Issue by Advik-B** [UN-GCPDS/qt-material#60]
## Before applying the theme
![image](https://user-images.githubusercontent.com/86160411/163704235-f1656e41-3c0a-4ba4-8fd3-1d48293d6739.png)

## After a applying `dark_cyan` theme
![image](https://user-images.githubusercontent.com/86160411/163704226-756b545d-19ee-4eeb-aad2-6b2a3fd61319.png)

**Comment by Advik-B** [comment]
NOTE: Ignore the big blue blob on the first image. That is my mouse

**Comment by YeisonCardona** [comment]
Hi @Advik-B 

Qt-Designer has layouts and spacers to handle sizes, spacings, and proportions.

Check this example.
[example.zip](https://github.com/UN-GCPDS/qt-material/files/8695275/example.zip)
