### ISSUE TITLE
Using `density_scale` <= -2.0 hides scrollbars

### ISSUE THREAD

**Issue by nicoddemus** [UN-GCPDS/qt-material#64]
Hi,

Thanks again for the great library!

Using a `density_scale` value <= `-2.0` causes the scroll bars of views (tables, lists, etc) to disappear.

Consider this example:

```python
from PyQt5.QtWidgets import QApplication, QTableWidget
from qt_material import apply_stylesheet

app = QApplication([])
apply_stylesheet(app, theme='dark_teal.xml')
table = QTableWidget()
table.setRowCount(100)
table.setColumnCount(100)

table.show()
app.exec()
```

Produces this widget:

![image](https://user-images.githubusercontent.com/1085180/170580032-2c87d06a-9bbd-42ad-8310-5f33503537dc.png)

However, if we apply a `density_scale` of `-2.0`:

```python
from PyQt5.QtWidgets import QApplication, QTableWidget
from qt_material import apply_stylesheet

app = QApplication([])
apply_stylesheet(app, theme='dark_teal.xml', extra={"density_scale": -2.0}))
table = QTableWidget()
table.setRowCount(100)
table.setColumnCount(100)

table.show()
app.exec()

```

The scrollbars disappear:

![image](https://user-images.githubusercontent.com/1085180/170580224-a8628381-66bd-494a-a635-b605ca158d13.png)

Strangely, if we use something like `-1.99`, the scrollbars are OK (if a bit thin):

![image](https://user-images.githubusercontent.com/1085180/170580336-b8c40d9e-c614-47f2-9742-01c62d9eec75.png)

Is this a bug or expected behavior?

I'm using `density_scale` because I want the spacings, fonts, etc to be a bit smaller to get more screen size. Perhaps is there another way to accomplish this?

**Comment by YeisonCardona** [comment]
Hi, sorry for the late reply. I got distracted by my Mastery.
Now no element will have dimensions smaller than 4 pixels after scale calculations.

**Comment by nicoddemus** [comment]
Thanks for the fix, appreciate it!
