### ISSUE TITLE
Cannot change cell background color in QTableWidget

### ISSUE THREAD

**Issue by pysty1995** [UN-GCPDS/qt-material#65]
Hi,
Thanks for your hard work.

Currently i am having a issue that i cannot change QTableWidget cell background color when use "apply_stylesheet".
Without "apply_stylesheet" i am able to change the cell's property.
Please help.

**Comment by YeisonCardona** [comment]
Hi @pysty1995 

Did you check [this issue](https://github.com/UN-GCPDS/qt-material/issues/55)?

**Comment by pysty1995** [comment]
Thanks a lot.
