### ISSUE TITLE
Checkboxes not visible

### ISSUE THREAD

**Issue by lukasloetkolben** [UN-GCPDS/qt-material#7]
Checkboxes are not visible anymore when i apply the theme.

**Comment by nicoddemus** [comment]
I was about to open an issue and noticed this one.

Is this the problem you are describing?

![image](https://user-images.githubusercontent.com/1085180/101246434-0f343f80-36f2-11eb-8865-a5872f5dd5e0.png)

Here's the code I'm using (it uses the [pyqt5-material](https://github.com/FuturisticGoo/pyqt5-material) fork, but the theme should be identical):

```python
from PyQt5.QtWidgets import QApplication, QWidget, QHBoxLayout, QCheckBox, QPushButton
from pyqt5_material import apply_stylesheet

app = QApplication([])
apply_stylesheet(app, theme="dark_teal.xml")

widget = QWidget()

layout = QHBoxLayout(widget)
layout.addWidget(QCheckBox("Update automatically"))
layout.addWidget(QPushButton("Update"))

widget.show()
app.exec()

```

**Comment by lukasloetkolben** [comment]
Yes I have the same issue. Are the icons working for you? I opened another issue... Maybe checkboxes are using icons and that's the reason?

**Comment by nicoddemus** [comment]
You mean checked? Yes it is working:

![image](https://user-images.githubusercontent.com/1085180/101247594-41956b00-36f9-11eb-9d9a-e8f305a9a8e6.png)

**Comment by nicoddemus** [comment]
Ahh wait, nevermind, it is clearly a problem with `pyqt5-material`, I've updated my example to use PySide2 and pýside-material:

![image](https://user-images.githubusercontent.com/1085180/101250900-79ea7880-36fc-11eb-8ff8-cf39bc9b5bce.png)

Sorry for the noise, I will open an issue there.

**Comment by nicoddemus** [comment]
Unfortunately `pyqt5-material` doesn't have Issues enabled, so I can't open an issue there. cc'ing @FuturisticGoo in hopes he sees this.

**Comment by FuturisticGoo** [comment]
Thanks for mentioning. Unfortunately I might not be able to quickly fix this because of exams, but I've enabled issues in my repo now (I don't remember turning it off) so you can create an issue there. I had some problems merging material.css.template so I think it has something to do with that, might have to check.

**Comment by nicoddemus** [comment]
No worries, thanks a lot. Created https://github.com/FuturisticGoo/pyqt5-material/issues/1.

**Comment by YeisonCardona** [comment]
Hi @lukasloetkolben @nicoddemus @FuturisticGoo 
I just decided to make this project compatible with PyQt5, which means change the project name, so the troubles with the theme should be fixed now.

**Comment by nicoddemus** [comment]
Awesome news! Thanks a lot @YeisonCardona.

Also many thanks to @FuturisticGoo for creating the PyQt5 fork. 👍
