### ISSUE TITLE
Scroll Bar Background on Dark Themes

### ISSUE THREAD

**Issue by avenzi** [UN-GCPDS/qt-material#80]
OS: Windows 11
Python version: 3.9.0

With no extra styling (just the base theme), the QScrollBar appears to have a strange, checkered background texture in all the dark themes:

![screenshot](https://user-images.githubusercontent.com/122910948/213338121-f5e11e6f-3b58-4c89-8bf0-e89647ece946.png)

I was able to find the reason for this: https://stackoverflow.com/questions/17935691/stylesheet-on-qscrollbar-leaves-background-of-scrollbar-with-checkerboard-patter
Evidently this is due to the add-page and sub-page backgrounds not being set.

In order to get the scrollbar to display properly, I had to add the following custom styling:
```
QScrollBar::sub-page:horizontal,
QScrollBar::add-page:horizontal,
QScrollBar::sub-page:vertical,
QScrollBar::add-page:vertical,
QScrolLBar:vertical {
    background: transparent;
}
```

Is this intended? I'm not sure if this is simply due to my specific platform or something, but it seemed odd to me.

**Comment by YeisonCardona** [comment]
Hi, I will add your code in the default CSS styles since I cannot access a Windows machine :/
