### ISSUE TITLE
Why is all title uppercase by default?

### ISSUE THREAD

**Issue by CheerMan1** [UN-GCPDS/qt-material#81]
Why is all title uppercase by default?

**Comment by Atumyugi** [comment]
Hello, I also want to know

**Comment by CheerMan1** [comment]
You can override the original style

```
app = QApplication(sys.argv)
apply_stylesheet(app, "dark_teal.xml")
stylesheet = app.styleSheet()
with open('custom.css') as file:
    app.setStyleSheet(stylesheet + file.read().format(**os.environ))
```

#  custom.css
> QGroupBox {{
  text-transform: none;
  margin: 0px;
  padding: 20px 0px 10px 0px;
}}
QPushButton {{
  text-transform: none;
}}

**Comment by Atumyugi** [comment]
thanks，it's useful 😁
