### ISSUE TITLE
When version 2.13 is going to be officially published?

### ISSUE THREAD

**Issue by giumas** [UN-GCPDS/qt-material#83]
I have discovered that the option to set the `css_file` (added in https://github.com/UN-GCPDS/qt-material/commit/097bd2a06794b5ce0010f3209f26ea09df267c78#diff-9db3f8bed15a4c29ec7e56dd3f99ae5fb483b1d1ad85ecaf658b9ec6a551a8b6) is not available in version 2.12 (the latest one available in PyPI: https://pypi.org/project/qt-material/#history ). 

When is 2.13 going to be published?

**Comment by YeisonCardona** [comment]
Hi, I think that the ```V2.13``` was internal only :)
I just released the ```V2.14```, Thanks for your interest.
